Merge pull request #4522 from RosettaCommons/benchmark
- adding support for persistent Python virtual environments 
- disabling iPython history in notebook test
- fixing issue with index.html generation so PyRosetta release links should work again
- unifying Conda package requirements across unit tests and release.conda
-fixing release tests on B3 back-ends
- removing individual virtual env setup from integration tests
- updating Python versions

Old repository SHA1: bfd3717efec500fd69da8009486e078f1160779b

diff --git a/tests/integration/tests/auto-drrafter_final_results/command b/tests/integration/tests/auto-drrafter_final_results/command
--- a/tests/integration/tests/auto-drrafter_final_results/command
+++ b/tests/integration/tests/auto-drrafter_final_results/command
@@ -52,14 +52,14 @@ date > start-time.ignore
 # Here's a typical test for a Mini binary, assuming there's a "flags" file
 # in this directory too:
 
-TESTPYTHON=`which python3`
-%(python3)s -m venv virtual_env_for_networkx >> install_log.ignore 2>&1
-source virtual_env_for_networkx/bin/activate >> install_log.ignore 2>&1
-if [[ "$TESTPYTHON" == "`which python3`" ]] ; then
-    echo "Awful! Environment activation failed." >> install_log.ignore
-    exit 1
-fi
-`which python3` -m pip install networkx mrcfile >> install_log.ignore 2>&1
+# TESTPYTHON=`which python3`
+# %(python3)s -m venv virtual_env_for_networkx >> install_log.ignore 2>&1
+# source virtual_env_for_networkx/bin/activate >> install_log.ignore 2>&1
+# if [[ "$TESTPYTHON" == "`which python3`" ]] ; then
+#     echo "Awful! Environment activation failed." >> install_log.ignore
+#     exit 1
+# fi
+# `which python3` -m pip install networkx mrcfile >> install_log.ignore 2>&1
 
 `which python3` %(minidir)s/src/apps/public/DRRAFTER/auto-DRRAFTER_setup_next_round.py -out_pref mini_example -curr_round FINAL_R3 -nmodels 10 -rosetta_directory %(bin)s/ -rosetta_extension .%(binext)s -test  2>&1 \
     | egrep -vf ../../ignore_list \
@@ -69,8 +69,8 @@ fi
     | egrep -vf ../../ignore_list \
     >> log
 
-deactivate 
-rm -r virtual_env_for_networkx install_log.ignore
+# deactivate
+# rm -r virtual_env_for_networkx install_log.ignore
 
 
 test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so
diff --git a/tests/integration/tests/auto-drrafter_setup_run_R1/command b/tests/integration/tests/auto-drrafter_setup_run_R1/command
--- a/tests/integration/tests/auto-drrafter_setup_run_R1/command
+++ b/tests/integration/tests/auto-drrafter_setup_run_R1/command
@@ -52,14 +52,14 @@ date > start-time.ignore
 # Here's a typical test for a Mini binary, assuming there's a "flags" file
 # in this directory too:
 
-TESTPYTHON=`which python3`
-%(python3)s -m venv virtual_env_for_networkx >> install_log.ignore 2>&1 
-source virtual_env_for_networkx/bin/activate >> install_log.ignore 2>&1 
-if [[ "$TESTPYTHON" == "`which python3`" ]] ; then
-    echo "Awful! Environment activation failed." >> install_log.ignore 2>&1
-    exit 1
-fi
-`which python3` -m pip install networkx mrcfile >> install_log.ignore 2>&1
+# TESTPYTHON=`which python3`
+# %(python3)s -m venv virtual_env_for_networkx >> install_log.ignore 2>&1
+# source virtual_env_for_networkx/bin/activate >> install_log.ignore 2>&1
+# if [[ "$TESTPYTHON" == "`which python3`" ]] ; then
+#     echo "Awful! Environment activation failed." >> install_log.ignore 2>&1
+#     exit 1
+# fi
+# `which python3` -m pip install networkx mrcfile >> install_log.ignore 2>&1
 
 `which python3` %(minidir)s/src/apps/public/DRRAFTER/auto-DRRAFTER_setup.py -map_thr 30 -full_dens_map input_files/map.mrc -full_dens_map_reso 10.0 -fasta input_files/fasta.txt -secstruct input_files/secstruct.txt -out_pref mini_example -rosetta_directory %(bin)s/ -rosetta_extension .%(binext)s -repeats 1 -shift_center -nstruct_per_job 1 -cycles 200 -fit_only_one_helix -test  2>&1 \
     | egrep -vf ../../ignore_list \
@@ -70,11 +70,10 @@ fi
     >> log
 
 test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so
-
-deactivate
-rm -r virtual_env_for_networkx install_log.ignore
-
 # ^^^^ you want to add this line after each call to app-protocol in case they terminate abnormally
+
+# deactivate
+# rm -r virtual_env_for_networkx install_log.ignore
 
 #
 # Or if you don't care whether the logging output changes:
