Exiting with exception now gives non-zero exit codes
Change the standard try/catch block such that exceptions cause the
program to exit with a non-zero exit code. As a consequence, (properly
written) integration tests will now correctly show when program exits
cleanly, or when it errors out. Update app_exception_handling to test
that applications exit with non-zero error codes when passed bogus options.

I somewhat arbitrarily picked "-1" as a general "something wrong's
happening here, what it is ain't exactly clear" code. This can certainly
be changed if anyone is so inclined. (One possibility is to embed the
exit code to use in the exception itself, in case we want to use it to
pass signals up the chain.)

Also, fix some dos-mode line endings issues.

** Integration test changes expected:

app_exception_handling - different command file.
jrelax - was erroring out with a bad option. Now fixed.

The following integration tests have errors, and should now continue to
fail until those errors are fixed:

swa_rna_gagu_20_append_floating_base_by_jump
swa_rna_gagu_17_append_floating_base
swa_rna_erraser
erraser_minimize
swm_nickedhelix

Old repository SHA1: fb4f575d973e63d5fb68df06bfbe4c61cecfe8aa

diff --git a/tests/integration/tests/app_exception_handling/command b/tests/integration/tests/app_exception_handling/command
--- a/tests/integration/tests/app_exception_handling/command
+++ b/tests/integration/tests/app_exception_handling/command
@@ -50,7 +50,12 @@ echo "App exception handling log" > log
 for app in %(bin)s/*.%(binext)s 
 do
 	app_prefix=$( echo $app | sed 's:.%(binext)s::' | sed 's:/: :g' | awk '{print $NF}')
-	eval "$app -nodelay  -bogus_input_option" >> log_${app_prefix} 2>&1 
+	eval "$app -nodelay  -bogus_input_option" >> log_${app_prefix} 2>&1
+	# On error, the application should exit with a non-zero status.
+	if [ $? -eq 0 ]; then 
+		 echo "Error does not result in non-zero exit code in application $app_prefix" >> log
+	fi
+	# Now check that the exception was handled appropriately
 	if [[ $( grep -i "abort"  log_${app_prefix} | wc -l ) -gt 0 ]]; then
 		 guilty=$( git blame --line-porcelain %(bin)s/../src/pilot_apps.src.settings.all | grep -B 12 ${app_prefix} | awk '$1 == "author"' | sed 's:author ::' )
 		 echo "Unhandled exceptions in application $app_prefix added by $guilty " $(date) >> log
