Update features schema to use bigint instead of UUID for struct_id.
***If you are using the Features Reporting framework this will make your current databases unreadable. Contact me for migration scripts***

This commit also fixes a variety of bugs in the features reporting framework that led to race conditions and other errors
on different backends. The bulk of the refactoring to int struct_id was done by Alex Ford (history lost during migration to git).

Features integration tests will change.

----
An additional 23 commit messages were squashed into this commit:
--
Add merge.sh to features_parallel integration test.
--
updating xml file for hts_io test to use 'batch_description' instead of 'sample_source'
--
fixing ScreeningFeatures to work properly with the int based struct_ids
--
Merging in updates from master so I can fix ScreeningFeatures
--
cleanup output for features_parallel integration test.
--
Make ReportToDB batch_name and batch_description the name and description columns in the batches table.
--
Make features_parallel integration test work again
--
Remove extraneous serial case from protocol::features::get_protocol_and_batch_id()
--
Fix FeaturesReporterTests unit test.
--
Merge branch 'master' into origin-tjacobs2-int_struct_id

Conflicts:
	source/src/basic/options/keys/OptionKeys.cc.gen2.hh
	source/src/basic/options/keys/OptionKeys.cc.gen3.hh
	source/src/basic/options/option.cc.gen.hh
--
Merge branch 'tjacobs2/int_struct_id' of github.com:RosettaCommons/main into origin-tjacobs2-int_struct_id

Conflicts:
	source/src/basic/options/option.cc.gen.hh
--
Fix database_session_resource integration test
--
Fix database_jd2_compact_io integration test
--
Convert sample_source to batch_description in RosettaScripts:ReportToDB tag.
--
update options
--
Addint default value for -inout:dbms:database_partition

This was necessary because otherwise the if statement on src/basic/database/sql_utils.cc:389 failed.
option::operation[] only works if the flag is active. At this point the struct_id refactor works with mysql using both
the ReportToDB mover and the DatabaseJobOutputter in both serial and mpi distribution.

However, it fails if you try to use both the ReportToDB mover and the DatabaseJobOutputter at the same time.  that comes next
--
Really dont open two transactions at once
--
don't open two simultaneous transactions
--
move any references to uuid to new StructureID
--
removing the uuid stuff from sewing
--
update devel.src.settings to include sewing stuff
--
merging in svn changes, including the rename to the new directory structure
--
Moving over the int struct id branch. This branch history was a complete mess due to merging of
multiple git-svn repositories, and thus the branch was moved without retainment
--

Old repository SHA1: 460708cbc2a6846d9c39e53b6e14b67cf982d69a

Co-authored-by: Tim Jacobs <timjacobs2@gmail.com>
Co-authored-by: Sam DeLuca <sam@decarboxy.com>
Co-authored-by: Tim Jacobs <TimJacobs2@gmail.com>

diff --git a/tests/integration/tests/features_parallel/command b/tests/integration/tests/features_parallel/command
--- a/tests/integration/tests/features_parallel/command
+++ b/tests/integration/tests/features_parallel/command
@@ -26,44 +26,44 @@
 # All command files should start with this line:
 #
 
-#cd %(workdir)s
-#
-#[ -x %(bin)s/rosetta_scripts.%(binext)s ] || exit 1
-#
-#%(bin)s/rosetta_scripts.%(binext)s @flags_01 -database %(database)s  2>&1 \
-#	| egrep -vf ../../ignore_list \
-#	> log_db_output_01
-#
-#test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so (i.e. Tell testing system if Rosetta died.)
-#
-#%(bin)s/rosetta_scripts.%(binext)s @flags_02 -database %(database)s  2>&1 \
-#	| egrep -vf ../../ignore_list \
-#	> log_db_output_02
-#
-#test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so (i.e. Tell testing system if Rosetta died.)
-#
-#full_db="features_IntegrationTest.db3"
-#part_dbs=${full_db}_*
-#
-## this test requires 'bash' not just 'sh':
-#if type -P sqlite3 &>/dev/null; then
-#
-#   python merge_databases.py $full_db $part_dbs
-#
-#   # strip out information that will cause needless integrationt test failures
-#   sqlite3 $full_db 'UPDATE protocols SET svn_url = "";'
-#   sqlite3 $full_db 'UPDATE protocols SET svn_version = "";'
-#   
-#   # just consider dumped contents for easier integrationt test comparison
-#   sqlite3 $full_db '.dump' > $full_db.dump 
-#   for part_db in $part_dbs
-#   do
-#      sqlite3 $part_db '.dump' > $part_db.dump
-#   done
-#else
-#   echo "Please install the sqlite3 command line application to correctly run this test." > log_db_output
-#fi
-#
-#
-#rm -rf $full_db $part_dbs
+cd %(workdir)s
+
+[ -x %(bin)s/rosetta_scripts.%(binext)s ] || exit 1
+
+%(bin)s/rosetta_scripts.%(binext)s @flags_01 -database %(database)s  2>&1 \
+	| egrep -vf ../../ignore_list \
+	> log_db_output_01
+
+test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so (i.e. Tell testing system if Rosetta died.)
+
+%(bin)s/rosetta_scripts.%(binext)s @flags_02 -database %(database)s  2>&1 \
+	| egrep -vf ../../ignore_list \
+	> log_db_output_02
+
+test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so (i.e. Tell testing system if Rosetta died.)
+
+full_db="features_IntegrationTest.db3"
+part_dbs=${full_db}_*
+
+# this test requires 'bash' not just 'sh':
+if type -P sqlite3 &>/dev/null; then
+
+   bash merge.sh $full_db $part_dbs &> log_database_merge
+
+   # strip out information that will cause needless integrationt test failures
+   sqlite3 $full_db 'UPDATE protocols SET svn_url = "";'
+   sqlite3 $full_db 'UPDATE protocols SET svn_version = "";'
+   
+   # just consider dumped contents for easier integrationt test comparison
+   sqlite3 $full_db '.dump' > $full_db.dump 
+   for part_db in $part_dbs
+   do
+      sqlite3 $part_db '.dump' > $part_db.dump
+   done
+else
+   echo "Please install the sqlite3 command line application to correctly run this test." > log_db_output
+fi
+
+
+rm -rf $full_db $part_dbs
 
