Merge pull request #4087 from RosettaCommons/kkappel1/drrafter_updates
On behalf of @kkappel1: DRRAFTER updates

Old repository SHA1: 91b7a940f06ab065a81d9ce3046b08eef0de0b31

Co-authored-by: kkappel1 <kappel@stanford.edu>

diff --git a/tests/integration/tests/drrafter_setup_protein_dock/command b/tests/integration/tests/drrafter_setup_protein_dock/command
--- a/tests/integration/tests/drrafter_setup_protein_dock/command
+++ b/tests/integration/tests/drrafter_setup_protein_dock/command
@@ -51,11 +51,23 @@ date > start-time.ignore
 # Here's a typical test for a Mini binary, assuming there's a "flags" file
 # in this directory too:
 
-%(python2)s %(minidir)s/src/apps/public/DRRAFTER/DRRAFTER.py -fasta fasta.txt -secstruct secstruct.txt -start_struct unbound_protein_plus_RNA_helix.pdb -map_file empty_2bh2_bound_full.5.00.mrc -map_reso 5.0 -residues_to_model C:834-863 -include_residues_around A:114 -include_as_rigid_body helix_1_aligned_5.pdb protein_2.pdb -job_name test 2>&1 \
+TESTPYTHON=`which python3`
+%(python3)s -m venv virtual_env_for_networkx && source virtual_env_for_networkx/bin/activate 
+if [ "$TESTPYTHON" -eq `which python3` ] ; then
+    echo "Awful! Environment activation failed."
+    exit 1
+fi
+`which python3` -m pip install networkx mrcfile
+
+`which python3` %(minidir)s/src/apps/public/DRRAFTER/DRRAFTER.py -fasta fasta.txt -secstruct secstruct.txt -start_struct unbound_protein_plus_RNA_helix.pdb -map_file empty_2bh2_bound_full.5.00.mrc -map_reso 5.0 -residues_to_model C:834-863 -include_residues_around A:114 -include_as_rigid_body helix_1_aligned_5.pdb protein_2.pdb -job_name test 2>&1 \
     | egrep -vf ../../ignore_list \
     > log
 
 test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so
+
+deactivate
+rm -r virtual_env_for_networkx
+
 # ^^^^ you want to add this line after each call to app-protocol in case they terminate abnormally
 
 #
diff --git a/tests/integration/tests/drrafter_setup_ribosome_test/command b/tests/integration/tests/drrafter_setup_ribosome_test/command
--- a/tests/integration/tests/drrafter_setup_ribosome_test/command
+++ b/tests/integration/tests/drrafter_setup_ribosome_test/command
@@ -51,11 +51,23 @@ date > start-time.ignore
 # Here's a typical test for a Mini binary, assuming there's a "flags" file
 # in this directory too:
 
-%(python2)s %(minidir)s/src/apps/public/DRRAFTER/DRRAFTER.py -fasta full_fasta.txt -secstruct full_secstruct_fix.txt -map_file empty_emd_2490.mrc -map_reso 4.9 -residues_to_model A:883-893 -job_name test -no_csts -start_struct start_thread_3.pdb -no_initial_structures  2>&1 \
+TESTPYTHON=`which python3`
+%(python3)s -m venv virtual_env_for_networkx && source virtual_env_for_networkx/bin/activate 
+if [ "$TESTPYTHON" -eq `which python3` ] ; then
+    echo "Awful! Environment activation failed."
+    exit 1
+fi
+`which python3` -m pip install networkx mrcfile
+
+`which python3` %(minidir)s/src/apps/public/DRRAFTER/DRRAFTER.py -fasta full_fasta.txt -secstruct full_secstruct_fix.txt -map_file empty_emd_2490.mrc -map_reso 4.9 -residues_to_model A:883-893 -job_name test -no_csts -start_struct start_thread_3.pdb -no_initial_structures  2>&1 \
     | egrep -vf ../../ignore_list \
     > log
 
 test "${PIPESTATUS[0]}" != '0' && exit 1 || true  # Check if the first executable in pipe line return error and exit with error code if so
+
+deactivate
+rm -r virtual_env_for_networkx
+
 # ^^^^ you want to add this line after each call to app-protocol in case they terminate abnormally
 
 #
